SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- APPOINTMENTS table
CREATE TABLE [dbo].[Appointments]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[Date] DATETIME NOT NULL,
	[DoctorId] NVARCHAR(450) NOT NULL,
	[CanceledById] NVARCHAR(450) NULL,
	[CanceledOn] DATETIME NULL,
CONSTRAINT [PK_Appointments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

ALTER TABLE [dbo].[Appointments] WITH CHECK
ADD CONSTRAINT [FK_Appointments_Users_UserId] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Appointments]
CHECK CONSTRAINT [FK_Appointments_Users_UserId]
GO

ALTER TABLE [dbo].[Appointments] WITH CHECK
ADD CONSTRAINT [FK_Appointments_Users_DoctorId] FOREIGN KEY ([DoctorId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Appointments]
CHECK CONSTRAINT [FK_Appointments_Users_DoctorId]
GO

ALTER TABLE [dbo].[Appointments] WITH CHECK
ADD CONSTRAINT [FK_Appointments_Users_CanceledById] FOREIGN KEY ([CanceledById])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Appointments]
CHECK CONSTRAINT [FK_Appointments_Users_CanceledById]
GO

-- RATINGS table
CREATE TABLE [dbo].[Ratings]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[ByUserId] NVARCHAR(450) NOT NULL,
	[Value] BIT NOT NULL,
CONSTRAINT [PK_Ratings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

ALTER TABLE [dbo].[Ratings] WITH CHECK
ADD CONSTRAINT [FK_Ratings_Users_UserId] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Ratings]
CHECK CONSTRAINT [FK_Ratings_Users_UserId]
GO

ALTER TABLE [dbo].[Ratings] WITH CHECK
ADD CONSTRAINT [FK_Ratings_Users_ByUserId] FOREIGN KEY ([ByUserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Ratings]
CHECK CONSTRAINT [FK_Ratings_Users_ByUserId]
GO

-- COMMENTS table
CREATE TABLE [dbo].[Comments]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Text] NVARCHAR(256) NOT NULL,
	[ByUserId] NVARCHAR(450) NOT NULL,
	[UserId] NVARCHAR(450) NULL,
	[EventId] INT NULL,
CONSTRAINT [PK_Comments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

ALTER TABLE [dbo].[Comments] WITH CHECK
ADD CONSTRAINT [FK_Comments_Users_UserId] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Comments]
CHECK CONSTRAINT [FK_Comments_Users_UserId]
GO

ALTER TABLE [dbo].[Comments] WITH CHECK
ADD CONSTRAINT [FK_Comments_Users_ByUserId] FOREIGN KEY ([ByUserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Comments]
CHECK CONSTRAINT [FK_Comments_Users_ByUserId]
GO

ALTER TABLE [dbo].[Comments] WITH CHECK
ADD CONSTRAINT [FK_Comments_Events_EventId] FOREIGN KEY ([EventId])
REFERENCES [dbo].[Events] ([Id])
GO

ALTER TABLE [dbo].[Comments]
CHECK CONSTRAINT [FK_Comments_Events_EventId]
GO

-- EVENTS table
CREATE TABLE [dbo].[Events]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[Title] NVARCHAR(128) NOT NULL,
	[Text] NVARCHAR(256) NOT NULL,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

ALTER TABLE [dbo].[Events] WITH CHECK
ADD CONSTRAINT [FK_Events_Users_UserId] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Events]
CHECK CONSTRAINT [FK_Events_Users_UserId]
GO