SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TODO: Foreign keys
CREATE TABLE [dbo].[Appointments]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[Date] DATETIME NOT NULL,
	[DoctorId] NVARCHAR(450) NOT NULL,
	[CanceledById] NVARCHAR(450) NULL,
	[CanceledOn] DATETIME NULL,
CONSTRAINT [PK_Appointments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

-- TODO: Foreign keys
CREATE TABLE [dbo].[Ratings]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[ByUserId] NVARCHAR(450) NOT NULL,
	[Value] BIT NOT NULL,
CONSTRAINT [PK_Ratings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

-- TODO: Foreign keys
CREATE TABLE [dbo].[Comments]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Text] NVARCHAR(256) NOT NULL,
	[ByUserId] NVARCHAR(450) NOT NULL,
	[UserId] NVARCHAR(450) NULL,
	[EventId] INT NULL,
CONSTRAINT [PK_Comments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO

-- TODO: Foreign keys
CREATE TABLE [dbo].[Events]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[UserId] NVARCHAR(450) NOT NULL,
	[Title] NVARCHAR(128) NOT NULL,
	[Text] NVARCHAR(256) NOT NULL,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
	WITH
	(
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)
GO